---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Install packages
  - from-file: packages.yml

  - type: kargs
    kargs:
      - preempt=full
      - nohz_full=all
      - threadirqs

  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - "com.github.tchx84.Flatseal"
          - "com.protonvpn.www"
          - "com.spotify.Client"
          - "dev.vencord.Vesktop"
          - "org.mozilla.firefox"
          - "org.pulseaudio.pavucontrol"

  - type: systemd
    system:
      enabled:
        - snapper-timeline.timer
        - snapper-cleanup.timer
        - scx_loader.service

  - type: signing
