---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Use rpmfusion instead of negativo17
  - type: bling
    install:
      - "rpmfusion"

  # Install packages
  - from-file: packages.yml

  - type: signing
