---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/aurora
image-version: stable

# Build custom packages
stages:
  - from-file: stages/mpv-uosc.yml
  - from-file: stages/mpv-thumbfast.yml

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Install fedora packages
  - from-file: packages.yml

  # Install custom packages
  - type: copy
    from: mpv-uosc
    src: /pkgbuild/build
    dest: /
  - type: copy
    from: mpv-thumbfast
    src: /pkgbuild/build
    dest: /

  - type: signing
